"use client";

import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import "../styles/globals.scss";
import gsap from "gsap";
import { ScrollTrigger } from "gsap/ScrollTrigger";
import { ScrollSmoother } from "gsap/ScrollSmoother";
import { useEffect } from "react";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

gsap.registerPlugin(ScrollTrigger, ScrollSmoother);

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  useEffect(() => {}, []);

  return (
    <html lang="en">
      <body>
        <div id="smooth-wrapper">
          <div id="smooth-content">{children} </div>
        </div>
      </body>
    </html>
  );
}
